- hosts: demo
  become: true
  tasks:
  - name: Install git, maven 
    package: name={{item}} state=present
    loop:
     - git
     - maven
  - name: Clone the code on the worker nodes from github
    git: repo=https://github.com/akshu20791/DevOpsClassCodes dest=/tmp/test
  - name: Execute maven command to build the code
    command: chdir=/tmp/test mvn verify
